'use client';
import { useLocale } from '@/components/locale-provider';
import Link from 'next/link';
import { ArrowUpRight, Check, ArrowRight, Network, ShieldCheck, Truck, Leaf, MoveUpRight } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { getProducts, getFAQs, Product } from '@/lib/catalog';
export function ProductCard({ product: p }: {
    product: Product;
}) { const { t, link, locale } = useLocale(); return <Link href={link(`/produk/${p.slug}`)} className="product-card"><div className="product-image"><img src={`/images/${p.image}.jpg`} alt={t("Ilustrasi bahan ") + (p.name.toLowerCase())} loading="lazy" width="600" height="400"/><span className="product-category">{p.category}</span></div><div className="product-info"><h3>{p.name}</h3><div className="english">{p.english}</div><p>{p.description}</p><div className="product-foot"><span>{t("Kenali produk")}</span><span className="circle-button"><ArrowUpRight size={18}/></span></div></div></Link>; }
export function ProductSection() { const { t, link, locale } = useLocale(); const products = getProducts(locale); return <section className="section product-section"><div className="shell"><div className="section-head" data-reveal><div><div className="eyebrow">{t("02 / Pilihan biomassa")}</div><h2>{t("Potensi alam.")}<br />{t("Energi untuk industri.")}</h2></div><Link className="btn btn-light" href={link("/produk")}>{t("Lihat semua produk")}<ArrowUpRight size={17}/></Link></div><div className="product-grid" data-reveal>{products.slice(0, 3).map(p => <ProductCard key={p.slug} product={p}/>)}</div><div className="catalog-note">{t("Enam pilihan biomassa, disesuaikan dengan kebutuhan Anda.")}<Link href={link("/produk")}>{t("Temukan yang sesuai ")}<ArrowRight size={15}/></Link></div></div></section>; }
export function Benefits() { const { t, link, locale } = useLocale(); const items = [{ icon: ShieldCheck, title: t("Mutu yang dapat dibahas"), text: t("Spesifikasi, hasil uji, dan kebutuhan sampel menjadi dasar pemilihan produk.") }, { icon: Network, title: t("Kolaborasi yang terbuka"), text: t("Mempertemukan kebutuhan pembeli dengan potensi pasokan yang relevan.") }, { icon: Truck, title: t("Logistik sesuai kebutuhan"), text: t("Diskusikan volume, lokasi, kemasan, dan jadwal dalam satu rencana pengadaan.") }]; return <section className="section shell"><div className="section-head" data-reveal><div><div className="eyebrow">{t("03 / Cara kami memberi nilai")}</div><h2>{t("Lebih dari pasokan.")}<br />{t("Sebuah kemitraan.")}</h2></div><p>{t("Keputusan yang lebih baik dimulai dari informasi yang jelas dan kerja sama yang saling memahami.")}</p></div><div className="benefit-grid" data-reveal>{items.map((item, i) => <article key={item.title}><div className="benefit-top"><item.icon size={27} strokeWidth={1.4}/><span>0{i + 1}</span></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>; }
export function Partnership() { const { t, link, locale } = useLocale(); return <section className="partnership section"><div className="shell"><div className="section-head" data-reveal><div><div className="eyebrow">{t("04 / Tumbuh bersama")}</div><h2>{t("Satu ekosistem.")}<br />{t("Banyak kemungkinan.")}</h2></div><p>{t("Dari kebutuhan industri hingga potensi pasokan, setiap kolaborasi dimulai dengan percakapan.")}</p></div><div className="partner-grid" data-reveal><Link href={link("/kontak?jalur=pembeli")} className="partner-card"><span className="eyebrow">{t("UNTUK PEMBELI")}</span><h3>{t("Temukan energi")}<br />{t("untuk langkah berikutnya.")}</h3><p>{t("Sampaikan produk, volume, dan tujuan pengiriman. Mari susun kebutuhan pasokan Anda.")}</p><span className="partner-bottom">{t("Minta penawaran ")}<span className="circle-button"><ArrowUpRight size={22}/></span></span></Link><Link href={link("/kontak?jalur=pemasok")} className="partner-card supplier"><span className="eyebrow">{t("UNTUK PEMASOK")}</span><h3>{t("Potensi Anda.")}<br />{t("Peluang yang lebih luas.")}</h3><p>{t("Punya stok atau sumber biomassa? Kenalkan produk Anda dan mulai diskusi kemitraan.")}</p><span className="partner-bottom">{t("Tawarkan pasokan ")}<span className="circle-button"><ArrowUpRight size={22}/></span></span></Link></div></div></section>; }
export function Process() { const { t, link, locale } = useLocale(); const flows = [{ key: 'pembeli', label: t("Saya ingin membeli"), steps: [[t("Ceritakan kebutuhan"), t("Jenis produk, spesifikasi, volume, dan lokasi tujuan.")], [t("Cocokkan produk"), t("Diskusi mutu, hasil uji, serta sampel jika tersedia.")], [t("Sepakati penawaran"), t("Harga, pembayaran, kemasan, dan jadwal tertulis.")], [t("Rencanakan pengiriman"), t("Koordinasi pengangkutan dan pemeriksaan penerimaan.")]] }, { key: 'pemasok', label: t("Saya ingin memasok"), steps: [[t("Kenalkan pasokan"), t("Jenis bahan, lokasi stok, kapasitas, dan foto produk.")], [t("Evaluasi kesesuaian"), t("Tinjau spesifikasi, asal bahan, serta dokumen mutu.")], [t("Bahas kerja sama"), t("Sepakati volume, harga, pembayaran, dan pengangkutan.")], [t("Koordinasikan pasokan"), t("Rencanakan pemuatan, dokumentasi, dan pemeriksaan.")]] }]; return <section className="section shell" id="proses"><div className="section-head" data-reveal><div><div className="eyebrow">{t("Dari percakapan menuju kerja sama")}</div><h2>{t("Langkah yang jelas.")}<br />{t("Kolaborasi yang terarah.")}</h2></div></div><Tabs defaultValue="pembeli" className="process-tabs"><TabsList className="custom-tabs">{flows.map(f => <TabsTrigger key={f.key} value={f.key}>{f.label}</TabsTrigger>)}</TabsList>{flows.map(f => <TabsContent value={f.key} key={f.key}><div className="process-grid">{f.steps.map(([title, desc], i) => <article key={title}><div className="step-number">0{i + 1}<ArrowRight size={18}/></div><h3>{title}</h3><p>{desc}</p></article>)}</div></TabsContent>)}</Tabs></section>; }
export function FAQ() { const { t, link, locale } = useLocale(); const faqs = getFAQs(locale); return <section className="section shell" id="faq"><div className="faq-grid"><div><div className="eyebrow">{t("Hal yang ingin Anda ketahui")}</div><h2>{t("Mulai dengan")}<br />{t("jawaban yang jelas.")}</h2><p className="muted faq-intro">{t("Belum menemukan jawabannya? Tim kami siap berdiskusi.")}</p><Link className="text-link" href={link("/kontak")}>{t("Hubungi kami")}<MoveUpRight size={16}/></Link></div><Accordion>{faqs.map(([q, a], i) => <AccordionItem key={q} value={String(i)}><AccordionTrigger className="faq-question">{q}</AccordionTrigger><AccordionContent className="faq-answer">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>; }
export function Closing() { const { t, link, locale } = useLocale(); return <section className="closing-wrap shell"><div className="closing" data-reveal><div className="closing-icon"><Leaf size={30} strokeWidth={1.2}/></div><div><div className="eyebrow">THE FUTURE GROWS WITH US</div><h2>{t("Masa depan lebih hijau")}<br />{t("dimulai bersama.")}</h2></div><Link className="btn btn-lime" href={link("/kontak")}>{t("Mulai percakapan")}<ArrowUpRight size={18}/></Link></div></section>; }
export function Assurance() { const { t, link, locale } = useLocale(); return <div className="assurance"><Check size={18}/><p>{t("Spesifikasi akhir, ketersediaan, dan ketentuan pasokan dikonfirmasi dalam penawaran. Foto digunakan sebagai ilustrasi bahan.")}</p></div>; }
