export const CONTACT = { whatsapp: '6281271733304', phone: '0812-7173-3304', email: 'info@bioenergy.id', address: 'Gold Coast Office Tower, PIK, Jakarta Utara', maps: 'https://www.google.com/maps/search/?api=1&query=Gold+Coast+Office+Tower+PIK+Jakarta' };
export type Product = {slug:string;name:string;english:string;category:string;image:string;description:string;detail:string;uses:string[];checks:string[];source:string;credit:string};
export const products:Product[] = [
{slug:'cangkang-sawit',name:'Cangkang Kelapa Sawit',english:'Palm Kernel Shell',category:'Residu perkebunan',image:'palm-shell',description:'Potensi hasil samping kelapa sawit untuk kebutuhan bahan bakar biomassa industri.',detail:'Cangkang yang dipisahkan dalam pengolahan kelapa sawit dapat dimanfaatkan sebagai bahan baku energi biomassa. Pemilihan mutu dan kesesuaian dengan sistem pembakaran menjadi bagian penting dalam pengadaan.',uses:['Boiler biomassa','Kebutuhan panas industri','Co-firing sesuai spesifikasi'],checks:['Ukuran dan distribusi cangkang','Kadar serat serta material asing','Kadar air, abu, dan nilai kalor'],source:'https://link.springer.com/article/10.1007/s42452-019-0334-6',credit:'Sunday U. Azunna · CC BY 4.0'},
{slug:'serpihan-kayu',name:'Serpihan Kayu',english:'Wood Chips',category:'Biomassa kayu',image:'wood-chip',description:'Potongan kayu untuk kebutuhan energi, dengan ukuran sesuai sistem industri.',detail:'Serpihan kayu merupakan potongan bahan kayu dengan ukuran tertentu. Asal bahan, tingkat kebersihan, serta ukuran potongan perlu diperiksa agar sesuai dengan kebutuhan fasilitas pengguna.',uses:['Boiler berbahan bakar kayu','Sistem pemanas industri','Bahan baku pengolahan biomassa'],checks:['Ukuran serta keseragaman potongan','Jenis dan asal bahan kayu','Kadar air dan material asing'],source:'https://commons.wikimedia.org/wiki/File:Gfp-wood-chips.jpg',credit:'Yinan Chen · Domain publik'},
{slug:'pelet-kayu',name:'Pelet Kayu',english:'Wood Pellets',category:'Biomassa kayu',image:'wood-pellet',description:'Biomassa kayu yang dipadatkan menjadi pelet untuk penanganan yang praktis.',detail:'Pelet dibuat dari bahan kayu yang dipadatkan menjadi silinder. Kekuatan pelet, kandungan serbuk halus, dan karakter pembakaran perlu disesuaikan dengan peralatan pengguna.',uses:['Sistem pemanas pelet','Boiler industri yang kompatibel','Pasokan bahan bakar terkemas'],checks:['Diameter dan panjang pelet','Densitas, ketahanan, dan serbuk halus','Kadar air, abu, dan nilai kalor'],source:'https://commons.wikimedia.org/wiki/File:Pellets_hand.jpg',credit:'Tom Bruton · Domain publik'},
{slug:'serbuk-gergaji',name:'Serbuk Gergaji',english:'Sawdust',category:'Biomassa kayu',image:'sawdust',description:'Residu pengolahan kayu yang dapat diolah kembali menjadi bahan baku bernilai.',detail:'Serbuk gergaji berasal dari proses pengolahan kayu. Ukuran partikel, kadar air, serta kebersihan bahan menjadi pertimbangan penting sebelum digunakan dalam produksi atau sistem energi.',uses:['Bahan baku pelet dan briket','Pengolahan biomassa lanjutan','Sistem energi yang kompatibel'],checks:['Kehalusan partikel','Asal kayu dan kebersihan bahan','Kadar air serta kadar abu'],source:'https://commons.wikimedia.org/wiki/File:Sawdust..jpg',credit:'Noslenlou · CC BY-SA 4.0'},
{slug:'sekam-padi',name:'Sekam Padi',english:'Rice Husks',category:'Residu pertanian',image:'rice-husk',description:'Nilai baru dari hasil samping penggilingan padi untuk kebutuhan industri.',detail:'Sekam adalah lapisan pelindung bulir padi yang terpisah saat penggilingan. Karakter abu dan densitasnya perlu dipertimbangkan dalam pemilihan sistem penyimpanan dan pembakaran.',uses:['Boiler khusus sekam','Bahan baku briket','Pengolahan hasil samping pertanian'],checks:['Kebersihan serta material asing','Kadar air dan densitas curah','Karakter abu dan nilai kalor'],source:'https://commons.wikimedia.org/wiki/File:Rice_husk.jpg',credit:'GST HBK · Domain publik'},
{slug:'cangkang-kelapa',name:'Cangkang Kelapa',english:'Coconut Shells',category:'Residu perkebunan',image:'coconut-shell',description:'Tempurung kelapa untuk kebutuhan biomassa dan bahan baku pengolahan lanjutan.',detail:'Tempurung kelapa dapat dimanfaatkan sebagai bahan baku energi maupun pengolahan arang. Kebersihan, ukuran pecahan, dan kadar air perlu disepakati sebelum pengadaan.',uses:['Bahan baku arang','Bahan baku karbon aktif melalui pengolahan','Kebutuhan energi termal'],checks:['Ukuran dan bentuk pecahan','Sisa sabut, daging, dan kontaminan','Kadar air, abu, dan nilai kalor'],source:'https://commons.wikimedia.org/wiki/File:Coconut_shells_as_fuel_for_the_kiln.jpg',credit:'HannoSEA · CC BY-SA 4.0'}
];
export const faqs=[['Bagaimana cara meminta penawaran?','Pilih produk dan isi kebutuhan Anda melalui halaman Kontak. Sertakan volume, lokasi tujuan, jadwal, serta spesifikasi yang dibutuhkan. Anda dapat meninjau ringkasan sebelum mengirimkannya melalui WhatsApp atau email.'],['Apakah tersedia hasil uji dan sampel produk?','Ketersediaan hasil uji laboratorium (COA), lembar spesifikasi, dan sampel perlu dikonfirmasi untuk produk serta sumber pasokan yang dipilih. Sampaikan kebutuhan dokumen dan pengujian sejak awal diskusi.'],['Berapa minimum pembelian dan waktu pengiriman?','Minimum pembelian, kapasitas yang tersedia, bentuk kemasan, dan waktu pengiriman bergantung pada produk, lokasi pasokan, serta tujuan. Tim akan membahasnya dalam penawaran yang sesuai dengan kebutuhan Anda.'],['Bagaimana cara menjadi mitra pemasok?','Pilih jalur “Tawarkan pasokan” pada halaman Kontak. Siapkan jenis produk, lokasi stok, kapasitas rutin, spesifikasi, dan dokumentasi bahan untuk proses diskusi dan evaluasi.'],['Bagaimana harga dan pembayaran ditentukan?','Harga dibahas berdasarkan spesifikasi, volume, lokasi, kemasan, dan kebutuhan logistik. Ketentuan pembayaran serta pengiriman disepakati dalam penawaran atau kontrak tertulis.'],['Bagaimana jika barang tidak sesuai spesifikasi?','Kriteria mutu, metode pemeriksaan, toleransi, dan penanganan ketidaksesuaian perlu disepakati sebelum pemesanan. Laporkan perbedaan dengan dokumentasi serta hasil pemeriksaan kepada tim.']];

import englishCatalog from './locales/catalog-en.json';
import type {Locale} from './i18n';
export function getProducts(locale:Locale):Product[]{
  if(locale==='id')return products;
  return products.map(product=>({...product,...englishCatalog.products.find(p=>p.slug===product.slug)}));
}
export function getFAQs(locale:Locale){return locale==='en'?englishCatalog.faqs:faqs;}
