import { getLocaleTools, type Locale } from '@/lib/i18n';
import { Suspense } from 'react';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, MapPin, MessageCircle, Mail, Clock } from 'lucide-react';
import { CONTACT } from '@/lib/catalog';
import { InquiryForm } from '@/components/inquiry-form';
import { FAQ } from '@/components/sections';
export default function Contact({ locale = 'id' }: {
    locale?: Locale;
} = {}) { const { t, link } = getLocaleTools(locale); return <main id="main"><section className="page-intro shell"><div className="breadcrumb"><Link href={link("/")}>{t("Beranda")}</Link><ArrowRight size={13}/><span>{t("Kontak")}</span></div><div className="page-intro-row"><div><div className="eyebrow">{t("KOLABORASI DIMULAI DI SINI")}</div><h1>{t("Ide yang baik.")}<br /><em>{t("Percakapan yang berarti.")}</em></h1></div><p>{t("Untuk kebutuhan pasokan, penawaran produk, atau diskusi kemitraan\u2014kami ingin mendengar dari Anda.")}</p></div></section><section className="contact-grid shell"><aside className="contact-sidebar"><div className="contact-item"><MapPin size={24}/><div><h3>{t("Temui kami")}</h3><p>Gold Coast Office Tower<br />{t("PIK, Jakarta Utara")}</p><a href={link(CONTACT.maps)} target="_blank" rel="noreferrer">{t("Lihat petunjuk arah \u2197")}</a></div></div><div className="contact-item"><MessageCircle size={24}/><div><h3>WhatsApp</h3><a href={link(`https://wa.me/${CONTACT.whatsapp}`)} target="_blank" rel="noreferrer">{CONTACT.phone}</a></div></div><div className="contact-item"><Mail size={24}/><div><h3>Email</h3><a href={link(`mailto:${CONTACT.email}`)}>{CONTACT.email}</a></div></div><div className="contact-item"><Clock size={24}/><div><h3>{t("Jam operasional")}</h3><p>{t("Senin\u2013Jumat \u00B7 08.00\u201317.00 WIB")}<br />{t("Sabtu \u00B7 08.00\u201312.00 WIB")}</p></div></div><div className="office-map"><img className="map-thumbnail" src="/images/indonesia.svg" alt={t("Peta Indonesia")} width="1000" height="400"/><h3>{t("Dari mana pun Anda memulai.")}</h3><p>{t("Sampaikan lokasi kebutuhan atau sumber pasokan Anda. Mari diskusikan kemungkinan kerja sama.")}</p><a className="text-link" href={link(CONTACT.maps)} target="_blank" rel="noreferrer">{t("Buka lokasi kantor")}<ArrowUpRight size={16}/></a></div></aside><Suspense fallback={<p>{t("Menyiapkan formulir...")}</p>}><InquiryForm /></Suspense></section><FAQ /></main>; }
